spring:
  application:
    name: chat-studio
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: db_chat
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      redisson:
        config: |
          singleServerConfig:
            idleConnectionTimeout: 10000
            connectTimeout: 10000
            timeout: 3000
            retryAttempts: 3
            retryInterval: 1500
            subscriptionsPerConnection: 5
            clientName: null
            address: "redis://127.0.0.1:6379"
            subscriptionConnectionMinimumIdleSize: 1
            subscriptionConnectionPoolSize: 50
            connectionMinimumIdleSize: 24
            connectionPoolSize: 64
            database: 0
            dnsMonitoringInterval: 5000
          threads: 16
          nettyThreads: 32
          codec: !<org.redisson.codec.JsonJacksonCodec> {}
          transportMode: "NIO"
  mail:
    password:
    default-encoding: utf-8
    host: smtp.163.com
    username:
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
  datasource:
    druid:
      initial-size: 10
      max-active: 128
      min-idle: 5
      max-wait: 80000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 30000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      filters: stat,wall,slf4j
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 10000
        slf4j:
          enabled: true
          statement-log-error-enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
      web-stat-filter:
        enabled: true
        url-pattern: /* # 过滤所有url
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" # 排除一些不必要的url
        session-stat-enable: true       # 开启session统计功能
        session-stat-max-count: 1000 # session的最大个数,默认100
      stat-view-servlet:
        enabled: true                   # 启用StatViewServlet
        url-pattern: /druid/* # 访问内置监控页面的路径，内置监控页面的首页是/druid/index.html
        reset-enable: false              # 不允许清空统计数据,重新计算
        login-username: root # 配置监控页面访问密码
        login-password: 123
        allow: 127.0.0.1 # 允许访问的地址，如果allow没有配置或者为空，则允许所有访问
        deny: # 拒绝访问的地址，deny优先于allow，如果在deny列表中，就算在allow列表中，也会被拒绝
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/chat_studio?useSSL=false&characterEncoding=utf-8&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mingge123

app:
  debug-mode: true

oss:
  endpoint: http://127.0.0.1:9000
  access-key: QEadxvmvguY3XYvpvkUM
  secret-key: ZCEeMEbx9Ckudm9V1Z1XOXSFdm8DW5KecSfNdgZ9
  default-bucket-name: default
  default-object-key-format: default_%s_%s.%s
  default-path-style-access: public
  doc:
    bucket-name: default-doc
    path-style-access: doc
    object-key-format: doc_%s_%s.%s

langchain4j:
  open-ai:
    embedding-model:
      api-key:
      model-name: text-embedding-v2
      dimensions: 1536
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
    streaming-chat-model:
      api-key:
      base-url: https://api.deepseek.com
      model-name: deepseek-chat
      temperature: 1.3
      max-retries: 0
    chat-model:
      api-key:
      base-url: https://api.deepseek.com
      model-name: deepseek-chat
      temperature: 1.3
      max-retries: 0

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    local-cache-scope: statement
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

sa-token:
  token-name: auth
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: ${app.debug-mode}

server:
  port: 8080
